### ISSUE TITLE
AmazonSQSException: MessageTooLong

### ISSUE THREAD

**Issue by sanjivr007** [softwaremill/elasticmq#146]
Not able to send long string on EMBEDDED server .

String theString2 = IOUtils.toString(new FileInputStream(new
                    File("/Users/sanjiv/Desktop/test.txt")));
 String length - 72093

Not able to send data on queue.

Exception - 

2018-07-24--09-07-32-264 [FIS TR: SP: RIP: LIP: T: U: D: S:] [SQSQueueBufferWorkerThread-7] ERROR com.<************>-  **Send report failed for queue** <*queuename*> : 
com.amazonaws.services.sqs.model.AmazonSQSException: **MessageTooLong;** see the SQS docs. **(Service: AmazonSQS; Status Code: 400; Error Code: MessageTooLong; Request ID: 00000000-0000-0000-0000-000000000000)**
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1665)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1641)
	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessageBatch(AmazonSQSClient.java:1538)
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$SendMessageBatchTask.process(SendQueueBuffer.java:512)
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$OutboundBatchTask.run(SendQueueBuffer.java:443)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mberlanda** [comment]
What is the size of your `/Users/sanjiv/Desktop/test.txt`?
AFAIK the max payload size for SQS is 256 kb: https://aws.amazon.com/about-aws/whats-new/2013/06/18/amazon-sqs-announces-256KB-large-payloads/

**Comment by sanjivr007** [comment]
Size of /Users/sanjiv/Desktop/test.txt is 72 KB on disk.

Is it same for elasticmq embedded server  ??
SQSRestServer server = SQSRestServerBuilder.withPort(MOCKSQS_PORT).withInterface(ENDPOINT).start();
serverUrl = server.waitUntilStarted().localAddress().getHostName() + ":" + server.waitUntilStarted().localAddress().getPort();

**Comment by thelinuxlich** [comment]
Since we have the option of payloads up to 2GB with the extended client library, couldn't we raise the limit?

**Comment by michalo2882** [comment]
Right now you can't change the limit, but it's possible to disable it via conf:
`rest-sqs {
  ...
  sqs-limits = relaxed
}`
