### ISSUE TITLE
Queues created using AWS SDK have incorrect host and port

### ISSUE THREAD

**Issue by kosmjon** [softwaremill/elasticmq#15]
com.amazonaws:aws-java-sdk:1.6.8 and org.elasticmq:elasticmq-rest-sqs_2.11:0.8.0 the following test fails since the resulting queueUrl value is http://localhost:9324
 @Test
  public void demoBadQueueUrl() {
    SQSRestServer sqsRestServer = SQSRestServerBuilder.withPort(60000).withInterface("10.39.136.164").start();
    AmazonSQSClient client = new AmazonSQSClient(new BasicAWSCredentials("x", "x"));
    client.setEndpoint("http://10.39.136.164:60000", "sqs", "");
    CreateQueueResult cqres = client.createQueue(new CreateQueueRequest("myqueue"));
    assertEquals("http://10.39.136.164:60000/queue/myqueue", cqres.getQueueUrl());
  }

**Comment by jimsingh** [comment]
I had a similar issue, but needed a stand alone solution. I used the code block below to search for a port and wait for the start future to complete. Adamw, it wasn't clear to me based on a brief read if you were waiting for the future to start, so it's possible the code below does nothing or waits on something arbitrary which adds just enough delay for the server socket to start listening.

```
  while (true) {
        try {
            int port = _sqsLastUsedPort.incrementAndGet();
            sqsRestServer = SQSRestServerBuilder
                    .withPort(port)
                    .withServerAddress(new NodeAddress("http", "localhost", port, ""))
                    .start();
            while (!sqsRestServer.startFuture().isCompleted()) {
                Thread.sleep(100);
            }
            break;
        } catch (Exception e) {
            if (tryCount++ >= MAX_SQS_PORT_TRIES) {
                throw new IllegalStateException("could not start elasticmq, retry could exceeded", e);
            }
        }
    }
```

**Comment by adamw** [comment]
@jimsingh `SQSRestServerBuilder.start()` doesn't wait for the future, but there's a `SQSRestServer.waitUntilStarted()` method which waits until completion (for a maximum of 1 minute), so you might want to use it here.

**Comment by bal1anD** [comment]
Hi @adamw I was having a similar issue and this post helped me in solving it. So thanks for the answers.
I have an alias set for my loopback address (lo0) something like 192.168.46.49 . This is because I need to access my host machine from my docker container. I was expecting http://192.168.46.49:9324  would get interpreted to http://localhost:9324 but it doesn't happen so. I would like to understand why does it not map the alias to localhost. Thanks.

**Comment by adamw** [comment]
@bal1anD not sure, by default the bind is to `0.0.0.0`, which is "all available interfaces". Are you using your alias when you specify the endpoint in the client? What kind of error are you getting?

**Comment by bal1anD** [comment]
@adamw : in my client, I'm using the alias this -->  http://192.168.46.49:9324 to connect to the ElasticMQ service (we have a stand-alone Java service which starts-up the elasticMq) , the error is the following in Docker :
`Exception in thread "main" com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.46.49:9324 [/192.168.46.49] failed: Connection refused
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1068)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1034)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
        at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
        at com.amazonaws.services.sqs.AmazonSQSClient.executeCreateQueue(AmazonSQSClient.java:718)
        at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:695)
        at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:730)
`

This started working when set the NetAddress and the withInterface() to the alias.

**Comment by adamw** [comment]
@bal1anD Sorry, but I don't really have a good clue why this might be happening. Maybe something in the client? Hard to say. But good that you have a work-around :)

**Comment by bal1anD** [comment]
Thanks @adamw , I'll look into the ElasticMQ to understand it better
