### ISSUE TITLE
Wrong and misleading error message for malformed ReceiveMessage request

### ISSUE THREAD

**Issue by igorsechyn** [softwaremill/elasticmq#207]
After upgrading to v014.7 I was getting an Unknown action error message when sending a request to receive messages without specifying queue url. This is the response error
```
{ InvalidAction: InvalidAction; see the SQS docs.
          at Request.extractError (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/protocol/query.js:50:29)
          at Request.callListeners (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
          at Request.emit (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:683:14)
          at Request.transition (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:685:12)
          at Request.callListeners (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
        message: 'InvalidAction; see the SQS docs.',
        code: 'InvalidAction',
        time: 2019-06-14T09:23:55.016Z,
        requestId: undefined,
        statusCode: 400,
        retryable: false,
        retryDelay: 87.76172590007063 
}
```
and the logs from the server
```
09:23:55.002 [elasticmq-akka.actor.default-dispatcher-2] WARN  o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Unknown action: ReceiveMessage

```
The same test on v0.14.6 produced this error
```
{ Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl): Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl); see the SQS docs.

          at Request.extractError (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/protocol/query.js:50:29)

          at Request.callListeners (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/sequential_executor.js:106:20)

          at Request.emit (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

          at Request.emit (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:683:14)

          at Request.transition (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:22:10)

          at AcceptorStateMachine.runTo (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/state_machine.js:14:12)

          at /opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/state_machine.js:26:10

          at Request.<anonymous> (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:38:9)

          at Request.<anonymous> (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/request.js:685:12)

          at Request.callListeners (/opt/jenkins/workspace/dev-tools-analytics-service_PR-7/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

        message:

         'Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl); see the SQS docs.',

        code:

         'Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl)',

        time: 2019-06-14T10:08:05.604Z,

        requestId: undefined,

        statusCode: 400,

        retryable: false,

        retryDelay: 90.54765048250417 }
```

During the test I was using aws-sdk for node version 2.475.0 and node version 10.16.0. elasticmq was running in docker using official images from docker hub

**Comment by Opalo** [comment]
@igorsechyn could please provide steps to reproduce this behaviour with CLI tools?

**Comment by cacilhas** [comment]
I’ve got the same error.

- The SQS connection is:

```scala
  lazy val SQS: AmazonSQS = AmazonSQSClientBuilder.standard()
    .withCredentials(credentialsProvider)
    .withEndpointConfiguration(sqsEndpoint)
    .build
```

- The request is:

```scala
  private val receiveRequest: ReceiveMessageRequest = new ReceiveMessageRequest(url)
    .withWaitTimeSeconds(40)
    .withMaxNumberOfMessages(1)
```

- And the routine:

```scala
      SQS receiveMessage receiveRequest getMessages() forEach(message => {
        deal(Json parse message.getBody)
        SQS deleteMessage(url, message getReceiptHandle)
      })
```

- The ElasticMQ startup log is:

```
22:54:40.349 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.14.12) ...
22:54:43.504 [elasticmq-akka.actor.default-dispatcher-4] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
22:54:43.580 [elasticmq-akka.actor.default-dispatcher-4] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(test,MillisVisibilityTimeout(30000),PT0S,PT0S,2019-09-05T22:54:43.517-03:00,2019-09-05T22:54:43.517-03:00,None,false,false,None,None,Map())
22:54:43.617 [elasticmq-akka.actor.default-dispatcher-4] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(test_fifo,MillisVisibilityTimeout(30000),PT0S,PT0S,2019-09-05T22:54:43.617-03:00,2019-09-05T22:54:43.617-03:00,None,true,false,None,None,Map())
22:54:43.621 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.14.12) started in 4084 ms ===
```

- And its error log is:

```
[WARN] [09/05/2019 23:00:54.442] [elasticmq-akka.actor.default-dispatcher-8] [akka.actor.ActorSystemImpl(elasticmq)] Illegal header: Illegal 'authorization' header: Invalid input '/', expected OWS, word, '=' or 'EOI' (line 1, column 29): AWS4-HMAC-SHA256 Credential=/20190906/elasticmq/sqs/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;host;user-agent;x-amz-date, Signature=31031ddf71d19a3666768e4189b3bd14954614dfe22e2f2b2346f113457ae5b9
                            ^
[WARN] [09/05/2019 23:00:55.064] [elasticmq-akka.actor.default-dispatcher-8] [akka.actor.ActorSystemImpl(elasticmq)] Illegal header: Illegal 'authorization' header: Invalid input '/', expected OWS, word, '=' or 'EOI' (line 1, column 29): AWS4-HMAC-SHA256 Credential=/20190906/elasticmq/sqs/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;host;user-agent;x-amz-date, Signature=4b888b4dec6a36c4ebf0d0ba0e169553a73eb035bf16a441adabac22a520bdb9
                            ^
23:00:55.095 [elasticmq-akka.actor.default-dispatcher-8] WARN  o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Unknown action: ReceiveMessage
```

**Comment by vincenteasy** [comment]
@cacilhas @igorsechyn did you find the solution to the problem? Please share if this is the case.

**Comment by kevcodez** [comment]
Running into the same issue, how did you solve it?

**Comment by kevcodez** [comment]
I was able to solve it by using the proper queue URL.

If you create a queue named "mails", the queue URL will be `http://localhost:<port>/queue/mails`. So it actually has **queue** in it's path before the actual queue name.
