### ISSUE TITLE
Support for case insensitive typed attributes

### ISSUE THREAD

**Issue by b0urb0n** [softwaremill/elasticmq#215]
I discovered the following error while working with `boto3` and ElasticMQ: https://github.com/boto/boto3/issues/2014:

It seems that `boto3` insists that MessageAttribute DataTypes be lower-cased and ElasticMQ insists that they're capitalized.

Relevant logs for ElasticMQ:

```
14:45:57.650 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.14.7) ...
14:45:58.451 [elasticmq-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:45:59.558 [elasticmq-akka.actor.default-dispatcher-2] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
14:45:59.559 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.14.7) started in 2539 ms ===
15:04:13.739 [elasticmq-akka.actor.default-dispatcher-8] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(tasks.fifo,MillisVisibilityTimeout(30000),PT0S,PT0S,2019-06-20T15:04:13.699-05:00,2019-06-20T15:04:13.699-05:00,None,true,false,None,None,Map())
15:27:53.627 [elasticmq-akka.actor.default-dispatcher-6] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(task.fifo,MillisVisibilityTimeout(30000),PT0S,PT0S,2019-06-20T15:27:53.626-05:00,2019-06-20T15:27:53.626-05:00,None,true,false,None,None,Map())
15:39:34.420 [elasticmq-akka.actor.default-dispatcher-6] ERROR o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Exception when running routes
java.lang.Exception: Currently only handles String, Number and Binary typed attributes
	at org.elasticmq.rest.sqs.SendMessageDirectives.$anonfun$getMessageAttributes$2(SendMessageDirectives.scala:84)
	at org.elasticmq.rest.sqs.SendMessageDirectives.$anonfun$getMessageAttributes$2$adapted(SendMessageDirectives.scala:62)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.elasticmq.rest.sqs.SendMessageDirectives.getMessageAttributes(SendMessageDirectives.scala:62)
	at org.elasticmq.rest.sqs.SendMessageDirectives.getMessageAttributes$(SendMessageDirectives.scala:47)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.getMessageAttributes(SQSRestServerBuilder.scala:107)
	at org.elasticmq.rest.sqs.SendMessageDirectives.doSendMessage(SendMessageDirectives.scala:95)
	at org.elasticmq.rest.sqs.SendMessageDirectives.doSendMessage$(SendMessageDirectives.scala:91)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.doSendMessage(SQSRestServerBuilder.scala:107)
	at org.elasticmq.rest.sqs.SendMessageDirectives.$anonfun$sendMessage$2(SendMessageDirectives.scala:28)
	at org.elasticmq.rest.sqs.directives.QueueDirectives.$anonfun$queueActorAndDataFromRequest$3(QueueDirectives.scala:31)
	at org.elasticmq.rest.sqs.directives.QueueDirectives.$anonfun$queueData$1(QueueDirectives.scala:80)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
15:40:37.857 [elasticmq-akka.actor.default-dispatcher-6] ERROR o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Exception when running routes
java.lang.Exception: Currently only handles String, Number and Binary typed attributes
	at org.elasticmq.rest.sqs.SendMessageDirectives.$anonfun$getMessageAttributes$2(SendMessageDirectives.scala:84)
	at org.elasticmq.rest.sqs.SendMessageDirectives.$anonfun$getMessageAttributes$2$adapted(SendMessageDirectives.scala:62)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.elasticmq.rest.sqs.SendMessageDirectives.getMessageAttributes(SendMessageDirectives.scala:62)
	at org.elasticmq.rest.sqs.SendMessageDirectives.getMessageAttributes$(SendMessageDirectives.scala:47)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.getMessageAttributes(SQSRestServerBuilder.scala:107)
	at org.elasticmq.rest.sqs.SendMessageDirectives.doSendMessage(SendMessageDirectives.scala:95)
	at org.elasticmq.rest.sqs.SendMessageDirectives.doSendMessage$(SendMessageDirectives.scala:91)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.doSendMessage(SQSRestServerBuilder.scala:107)
	at org.elasticmq.rest.sqs.SendMessageDirectives.$anonfun$sendMessage$2(SendMessageDirectives.scala:28)
	at org.elasticmq.rest.sqs.directives.QueueDirectives.$anonfun$queueActorAndDataFromRequest$3(QueueDirectives.scala:31)
	at org.elasticmq.rest.sqs.directives.QueueDirectives.$anonfun$queueData$1(QueueDirectives.scala:80)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by b0urb0n** [comment]
Closing.  Turns out I didn't RTFM enough...
