### ISSUE TITLE
NoSuchElementException when tag on SQS is set to nil

### ISSUE THREAD

**Issue by frncmx-form3** [softwaremill/elasticmq#511]
We use ElasticMQ via Localstack and that is provisioned with Terraform. Basically, the same way as we provision our real AWS infra. Recently, I came across a weird edge case when one of our TF module set an SQS tag to empty string, i.e., 

```terraform
resource "aws_sqs_queue" "queue" {
  name = "foobar"

  tags = {
    NoFoo = ""
  }
}
```
As that travels through the AWS TF provider and Localstack, somehow it reaches ElasticMQ as `nil` not as an empty string and that causes an exception. Plus the resource creation hangs. I'm not sure how and when the empty string turns into `nil`. However, maybe ElasticMQ should handle this edge case gracefully. So I decided to post this issue. 

## How to reproduce

I run ElasticMQ as `docker run --rm -p 9324:9324 softwaremill/elasticmq:1.1.1`

The way I reproduced the issue is with the following Go snippet:

```go
package main

import (
	"fmt"
	"net/http/httputil"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/sqs"
)

const elasticMQ = "http://localhost:9324"

func main() {
	client := newSQSClient()

	req, resp := client.CreateQueueRequest(&sqs.CreateQueueInput{
		Attributes: nil,
		QueueName:  aws.String(fmt.Sprintf("foobar-%d", time.Now().Unix())),
		Tags: map[string]*string{
			//"some": aws.String("foo"), // OK
			//"empty": aws.String(""), // OK
			"NoFoo": nil, // Exception
		},
	})

	panicOnErr(req.Build())
	dump(req)

	panicOnErr(req.Send())
	fmt.Println("New queue created with URL", *resp.QueueUrl)
}

func dump(req *request.Request) {
	result, err := httputil.DumpRequestOut(req.HTTPRequest, true)
	panicOnErr(err)

	fmt.Println("#####################################")
	fmt.Println(string(result))
	fmt.Println("#####################################")
}

func newSQSClient() *sqs.SQS {

	sess := session.Must(session.NewSessionWithOptions(session.Options{
		Config: aws.Config{
			Endpoint: aws.String(elasticMQ),
			Region:   aws.String("elasticmq"),
		},
	}))
	return sqs.New(sess)
}

func panicOnErr(err error) {
	if err != nil {
		panic(err)
	}
}

```

That dumps out the following request:
```http
Host: localhost:9324
User-Agent: aws-sdk-go/1.40.4 (go1.16.6; linux; amd64)
Transfer-Encoding: chunked
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept-Encoding: gzip

4f
Action=CreateQueue&QueueName=foobar-1626951909&Tag.1.Key=NoFoo&Version=2012-11-05
0

```

And ElasticMQ produces the following stacktrace:
```
11:05:10.413 [elasticmq-akka.actor.default-dispatcher-8] ERROR o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Exception when running routes
java.util.NoSuchElementException: key not found: Tag.1.Value
        at scala.collection.immutable.Map$Map4.apply(Map.scala:517)
        at org.elasticmq.rest.sqs.TagsModule$TagNameAndValuesReader.collect$1(TagsModule.scala:19)
        at org.elasticmq.rest.sqs.TagsModule$TagNameAndValuesReader.read(TagsModule.scala:23)
        at org.elasticmq.rest.sqs.CreateQueueDirectives$stateMachine$async$1.apply(CreateQueueDirectives.scala:83)
        at org.elasticmq.rest.sqs.CreateQueueDirectives$stateMachine$async$1.apply$mcV$sp(CreateQueueDirectives.scala:43)
        at org.elasticmq.rest.sqs.CreateQueueDirectives$stateMachine$async$1.apply(CreateQueueDirectives.scala:43)
        at org.elasticmq.rest.sqs.CreateQueueDirectives$stateMachine$async$1.apply(CreateQueueDirectives.scala:43)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by frncmx-form3** [comment]
Actually, looking at this one once more... the request dump looks a fishy. Where did the `Tag.1.Key` attribute go?

If I send the empty string version I get `&Tag.1.Key=empty&Tag.1.Value=&Version=2012-11-05` , which make a lot more sense.

Go version: 1.16
SDK: github.com/aws/aws-sdk-go v1.40.3
