### ISSUE TITLE
ERROR no matching constructor found on class akka.io.TcpIncomingConnection

### ISSUE THREAD

**Issue by pablodo** [softwaremill/elasticmq#552]
Version: 1.3.0

Hi everyone, we use this image at my company to run CircleCI Pipelines and now our projects are failing since the latest release with the following error:

```
[WARN  tini (87)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
15:43:53.193 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (1.3.0) ...
15:43:53.216 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
15:43:53.230 [elasticmq-akka.actor.default-dispatcher-7] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
15:43:53.232 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (1.3.0) started in 45 ms ===
15:43:53.232 [elasticmq-akka.actor.default-dispatcher-7] INFO  o.e.r.s.TheStatisticsRestServerBuilder - Started statistics rest server, bind address 0.0.0.0:9325
15:45:20.005 [elasticmq-akka.actor.default-dispatcher-6] ERROR akka.io.SelectionHandler$$anon$1 - no matching constructor found on class akka.io.TcpIncomingConnection for arguments [class akka.io.TcpExt, class sun.nio.ch.SocketChannelImpl, class akka.io.SelectionHandler$ChannelRegistryImpl, class akka.actor.FunctionRef, class scala.collection.immutable.Nil$, class java.lang.Boolean]
java.lang.IllegalArgumentException: no matching constructor found on class akka.io.TcpIncomingConnection for arguments [class akka.io.TcpExt, class sun.nio.ch.SocketChannelImpl, class akka.io.SelectionHandler$ChannelRegistryImpl, class akka.actor.FunctionRef, class scala.collection.immutable.Nil$, class java.lang.Boolean]
	at akka.util.Reflect$.error$1(Reflect.scala:89)
	at akka.util.Reflect$.findConstructor(Reflect.scala:113)
	at akka.actor.ArgsReflectConstructor.<init>(IndirectActorProducer.scala:99)
	at akka.actor.IndirectActorProducer$.apply(IndirectActorProducer.scala:64)
	at akka.actor.Props.producer(Props.scala:131)
	at akka.actor.Props.<init>(Props.scala:144)
	at akka.actor.Props$.apply(Props.scala:86)
	at akka.io.TcpListener.props$1(TcpListener.scala:137)
	at akka.io.TcpListener.$anonfun$acceptAllPending$1(TcpListener.scala:138)
	at akka.io.SelectionHandler.spawnChildWithCapacityProtection(SelectionHandler.scala:362)
	at akka.io.SelectionHandler$$anonfun$receive$1.applyOrElse(SelectionHandler.scala:317)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.SelectionHandler.aroundReceive(SelectionHandler.scala:302)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

```

**Comment by klobinoid** [comment]
Oh I see, my bad. We use the same setup as you pointed out, so I guess the issues might be connected. Let authors decide in which thread they will follow this issue.
