### ISSUE TITLE
Invalid request: MissingQueryParamRejection(QueueName), MissingQueryParamRejection(QueueUrl)

### ISSUE THREAD

**Issue by pancake-boy** [softwaremill/elasticmq#620]
failing to send message while sample code:

```
Error Invalid request: MissingQueryParamRejection(QueueName), MissingQueryParamRejection(QueueUrl): Invalid request: MissingQueryParamRejection(QueueName), MissingQueryParamRejection(QueueUrl); see the SQS docs.
    at Request.extractError (/Users/aaa/dev/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/aaa/dev/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/aaa/dev/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/aaa/dev/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/aaa/dev/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/aaa/dev/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/aaa/dev/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/aaa/dev/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/aaa/dev/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/aaa/dev/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'Invalid request: MissingQueryParamRejection(QueueName), MissingQueryParamRejection(QueueUrl)',
  time: 2022-01-10T11:11:52.092Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 61.140730084480246
}
```

```
include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

rest-stats {
  enabled = true
  bind-port = 9325
  bind-hostname = "0.0.0.0"
}

generate-node-address = false

queues {
   abc-queue{
        defaultVisibilityTimeout = 10 seconds
        delay = 5 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "abc-queue-dead-letters"
            maxReceiveCount = 3 // from 1 to 1000
        }
        fifo = false
    }
    abc-queue-dead-letters{ }
}

queues-storage {
}

aws {
  region = us-west-2
  accountId = aws-accountid
}
```

```
const params = {
      // Remove DelaySeconds parameter and value for FIFO queues
      DelaySeconds: 10,
      MessageAttributes: {
        Title: {
          DataType: 'String',
          StringValue: 'The Whistler',
        },
        Author: {
          DataType: 'String',
          StringValue: 'John Grisham',
        },
        WeeksOn: {
          DataType: 'Number',
          StringValue: '6',
        },
      },
      MessageBody:
        'Information about current NY Times fiction bestseller for week of 12/11/2016.',
      // MessageDeduplicationId: "TheWhistler",  // Required for FIFO queues
      // MessageGroupId: "Group1",  // Required for FIFO queues
      QueueUrl: `http://localhost:9324/aws-accountid/abc-queue`,
    };

    const sqs = new SQS({
      credentials: new Credentials('x', 'x'),
      region: 'us-west-2', // it does not matter
    });

    sqs.sendMessage(params, function (err, data) {
      if (err) {
        console.log('Error', err);
      } else {
        console.log('Success', data.MessageId);
      }
    });
```

**Comment by micossow** [comment]
Hi, the `aws-accountid` specified in `QueueUrl` should be a 12-digit number.
After https://github.com/softwaremill/elasticmq/pull/656 there'll be a more helpful error message returned

**Comment by micossow** [comment]
Fixed in https://github.com/softwaremill/elasticmq/releases/tag/v1.3.5
