### ISSUE TITLE
Sometimes fails to create server due to: javax.management.InstanceAlreadyExistsException: org.elasticmq:name=Queues

### ISSUE THREAD

**Issue by Kreinoee** [softwaremill/elasticmq#635]
Calling `.start` on the `SQSRestServerBuilder` sometimes fails with the following exception:

```
javax.management.InstanceAlreadyExistsException: org.elasticmq:name=Queues
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.elasticmq.rest.sqs.TheSQSRestServerBuilder.start(SQSRestServerBuilder.scala:246)
```

Looks like it happens in tests, where the server is booted up, and shutdown multiple times. I have for now worked around it, by catching the exception, waiting a second and then try again. 

I now that the tests sucessfully run multiple instances at the same time, and it is relatively rarely this happens and apparently by Random. So my best guess is some kind of race condition.

**Comment by micossow** [comment]
Exception handling added in https://github.com/softwaremill/elasticmq/releases/tag/v1.3.5
