### ISSUE TITLE
1.3.13 does not work with Java 8.

### ISSUE THREAD

**Issue by trackiss** [softwaremill/elasticmq#758]
After updating to version 1.3.13 with Java 8, I get the following exception:

```shell
java.lang.NoSuchMethodError: java.lang.String.isBlank()Z
	at org.elasticmq.NodeAddress.suffix(NodeAddress.scala:13)
	at org.elasticmq.NodeAddress.fullAddress(NodeAddress.scala:10)
	at org.elasticmq.rest.sqs.QueueURLModule.baseQueueURL(SQSRestServerBuilder.scala:441)
	at org.elasticmq.rest.sqs.QueueURLModule.baseQueueURL$(SQSRestServerBuilder.scala:424)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.baseQueueURL(SQSRestServerBuilder.scala:137)
	at org.elasticmq.rest.sqs.QueueURLModule.queueURL(SQSRestServerBuilder.scala:448)
	at org.elasticmq.rest.sqs.QueueURLModule.queueURL$(SQSRestServerBuilder.scala:447)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.queueURL(SQSRestServerBuilder.scala:137)
        # ...
```

This is probably a problem with the following changes That is, the `java.lang.String#isBlank` method only exists in Java 11 and later:

https://github.com/softwaremill/elasticmq/pull/755

https://github.com/softwaremill/elasticmq/blob/3d7685a0d647a8ceb39ac8c2a5e0b5a6b665ab1e/core/src/main/scala/org/elasticmq/NodeAddress.scala#L13

It requires either changing the code to work with Java 8 (maybe we should also test Java 8 on CI) or explicitly dropping Java 8 support.

**Comment by micossow** [comment]
Thanks for reporting the issue. It's fixed in https://github.com/softwaremill/elasticmq/releases/tag/v1.3.14
