### ISSUE TITLE
Could not find UI files error on 1.4.5-RC1 docker image

### ISSUE THREAD

**Issue by rcomesan** [softwaremill/elasticmq#887]
I'm using the latest docker image (softwaremill/elasticmq-native:1.4.5-RC1) and I noticed that the UI is no longer working. 

When I try to access 127.0.0.1:9325 I get an "Internal Server Error", and in the logs, I can see the following exception:

```
22:34:01.723 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (1.4.5-RC1) ...
22:34:01.741 [elasticmq-akka.actor.default-dispatcher-9] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
22:34:01.748 [main] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Metrics MBean org.elasticmq:name=Queues successfully registered
22:34:01.748 [elasticmq-akka.actor.default-dispatcher-11] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
22:34:01.749 [elasticmq-akka.actor.default-dispatcher-10] INFO  o.e.r.s.TheStatisticsRestServerBuilder - Started statistics rest server, bind address 0.0.0.0:9325
22:34:01.749 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (1.4.5-RC1) started in 28 ms ===
22:34:32.230 [elasticmq-akka.actor.default-dispatcher-11] ERROR o.e.r.s.TheStatisticsRestServerBuilder$$anon$1 - Exception when running routes
java.lang.RuntimeException: Could not find UI files
        at org.elasticmq.rest.stats.StatisticsDirectives.uiLocation(StatisticsDirectives.scala:50)
        at org.elasticmq.rest.stats.StatisticsDirectives.uiLocation$(StatisticsDirectives.scala:47)
        at org.elasticmq.rest.stats.TheStatisticsRestServerBuilder$$anon$1.uiLocation$lzycompute(StatisticsRestServerBuilder.scala:74)
        at org.elasticmq.rest.stats.TheStatisticsRestServerBuilder$$anon$1.uiLocation(StatisticsRestServerBuilder.scala:74)
        at org.elasticmq.rest.stats.StatisticsDirectives.$anonfun$serveUI$2(StatisticsDirectives.scala:95)
        at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
        at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:234)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:36)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:36)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
        at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:25)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
        at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
        at akka.http.scaladsl.server.Route$.$anonfun$createAsyncHandler$1(Route.scala:110)
        at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1430)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```
This problem is not present in version 1.4.4, so I imagine it's something recent.

Thanks a lot for this project, it's exactly what I needed.

**Comment by MarcAurel** [comment]
I also use the `latest` tag and I'm experiencing the same issue.

<details>
<summary>error logs (very similar to the message above) without any specific config</summary>

```
02:49:47.427 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (1.4.5-RC1) ...
02:49:47.443 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
02:49:47.452 [main] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Metrics MBean org.elasticmq:name=Queues successfully registered
02:49:47.452 [elasticmq-akka.actor.default-dispatcher-6] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
02:49:47.454 [elasticmq-akka.actor.default-dispatcher-6] INFO  o.e.r.s.TheStatisticsRestServerBuilder - Started statistics rest server, bind address 0.0.0.0:9325
02:49:47.454 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (1.4.5-RC1) started in 32 ms ===
02:49:49.451 [elasticmq-akka.actor.default-dispatcher-9] ERROR o.e.r.s.TheStatisticsRestServerBuilder$$anon$1 - Exception when running routes
java.lang.RuntimeException: Could not find UI files
        at org.elasticmq.rest.stats.StatisticsDirectives.uiLocation(StatisticsDirectives.scala:50)
        at org.elasticmq.rest.stats.StatisticsDirectives.uiLocation$(StatisticsDirectives.scala:47)
        at org.elasticmq.rest.stats.TheStatisticsRestServerBuilder$$anon$1.uiLocation$lzycompute(StatisticsRestServerBuilder.scala:74)
        at org.elasticmq.rest.stats.TheStatisticsRestServerBuilder$$anon$1.uiLocation(StatisticsRestServerBuilder.scala:74)
        at org.elasticmq.rest.stats.StatisticsDirectives.$anonfun$serveUI$2(StatisticsDirectives.scala:95)
        at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
        at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:234)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:36)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:36)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
        at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:25)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
        at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
        at akka.http.scaladsl.server.Route$.$anonfun$createAsyncHandler$1(Route.scala:110)
        at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1430)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```
</details>

IMHO, the `latest` tag should only point to stable releases, not RC versions. (looks like the behaviour to update `latest` tags are defined by the `dockerUpdateLatest` variables in [`build.sbt`](https://github.com/softwaremill/elasticmq/blob/master/build.sbt), and they're all set to `true`).

While this get fixed, I used the solution described in [this gist](https://gist.github.com/jclosure/b2bcf0686739ad6b79df#file-docker_reverting) to locally revert the tag `latest` to version 1.4.4.

**Comment by micossow** [comment]
Oops, sorry for that. I created version 1.4.5 and latest has been updated to that version.
