### ISSUE TITLE
"MD5 returned by SQS does not match the calculation on the original request" when using AWS JSON protocol and message attributes with custom data types

### ISSUE THREAD

**Issue by mgocd** [softwaremill/elasticmq#947]
**Description**

When receiving a SQS message with an attribute with a custom data type ([docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#message-attribute-data-types)) using AWS JSON protocol (AWS Java SDK v1 >= 1.12.584 / v2 >= 2.21.19), the following exception is thrown:

```
com.amazonaws.AmazonClientException: MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "b6ba7933bdd4077bb2cc8686b0146cfa", MD5 checksum returned: "6735a2d7fe7f0e962a51db579c2d92cb")
	at com.amazonaws.services.sqs.MessageMD5ChecksumHandler.receiveMessageResultMd5Check(MessageMD5ChecksumHandler.java:146)
	at com.amazonaws.services.sqs.MessageMD5ChecksumHandler.afterResponse(MessageMD5ChecksumHandler.java:87)
	at com.amazonaws.handlers.RequestHandler2Adaptor.afterResponse(RequestHandler2Adaptor.java:49)
```

An example message with a custom data type when the error occurs:

```
var request = new SendMessageRequest(
                getQueueUrl(endpoint),
                "msg"
        );
request.setMessageAttributes(Map.of(
        "timestamp", new MessageAttributeValue()
                .withStringValue("1")
                .withDataType("Number.java.lang.Long")
```

Minimal reproducible example (Java): https://github.com/mgocd/elasticmq-custom-attribute-data-type-issue
ElasticMQ version: 1.5.4

**Analysis**

This happens because [MessageAttributeSupport](https://github.com/softwaremill/elasticmq/blob/v1.5.4/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/MessageAttributesSupport.scala#L15) ignores custom data types when serializing to JSON (so `Number.java.lang.Long` becomes `Number`), while [SQSRestServerBuilder#md5AttributeDigest](https://github.com/softwaremill/elasticmq/blob/v1.5.4/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SQSRestServerBuilder.scala#L396) calculates MD5 digest correctly using the custom data type (`Number.java.lang.Long`).

**Proposed solution**

`MessageAttributesSupport` should use the custom data type when serializing to JSON.

A pull request will be proposed to fix the issue.

**Comment by micossow** [comment]
Release in `v1.5.5`
